### ISSUE TITLE
item The Nicker

### ISSUE THREAD

**Issue by morfisia** [mikeStr8s/ClassicBot#20] opened 2019-07-24 16:32 UTC
**Describe the bug**
no recognize this The Nicker.

**To Reproduce**
![thenicker](https://user-images.githubusercontent.com/32936214/61811254-66a97680-ae41-11e9-954d-3f23a6615cb6.PNG)

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by mikeStr8s** [comment] 2019-08-06 17:38
@morfisia please provide more detail on what your intended search was. What exact item you were looking to get back. While the screenshot is nice, I woulld like to have a little more context please :)

**Comment by Mitmocc** [comment] 2019-08-07 13:41
she is referring to this item https://classic.wowhead.com/item=13285/the-blackrock-slicer that was formerly known as the Nicker and had its name changed. So this is not a bug or issue.

**Comment by mikeStr8s** [comment] 2019-08-07 15:19
Because of the comment by @Mitmocc, I am closing this issue. Thank you @Mitmocc for your clerification.

**Closed by mikeStr8s** 2019-08-07 15:19 UTC
